name: ${project.artifactId}
main: com.jaoafa.PeriodMatch.PeriodMatch
version: ${project.version}
description: jao Minecraft Serverでよく使用される「.」を使った対決がいまここに…！
database: true
author: mine_book000
softdepend: [LunaChat, DiscordMC]
website: https://jaoafa.com/
commands:
   .:
      description: ピリオド対決を行います
      usage: /<command>
      permission: periodmatch.period
      permission-message: You do not have permission to perform this command.
   period:
      description: ピリオド対決の設定とかなんとかを行います
      usage: /<command>
      permission: periodmatch.period
      permission-message: You do not have permission to perform this command.